### ISSUE TITLE
Mis-parsing quotation marks in pragma directives,

### ISSUE THREAD

**Issue by fake-name** [idleberg/sublime-innosetup#7]
![image](https://cloud.githubusercontent.com/assets/1401239/23629062/541b6688-026b-11e7-9d48-0b5d23152421.png)

Basically, I have a `#pragma` line with the text: `#pragma message "Output folder name: " + FolderName`.

The latter double-quote mark seems to confuse the highlighting, and it sticks until the next line with a non-assignment directive

Version is current (I just installed it), v7.2.0.

Note that I *think* the issue is that the regex for `#pragma message` doesn't allow matching against colons (`:`). If I remove the colons, it highlights correctly. InnoSetup doesn't seem to have any issues with messages with colons in them, so I think that the correct solution is to allow their presence.

In this case, it's just debugging messages, but I can conceive of people needing the colons to be present.

**Comment by idleberg** [comment]
Thanks for reporting. Please see if v7.2.1 fixes this!

**Comment by fake-name** [comment]
That appears to have fixed the issue with the colons.

However, now the line `#define AppVer StringChange(FileRead(VerFile), '"', "")` is being mis-higlighted.

![image](https://cloud.githubusercontent.com/assets/1401239/23634182/ca402c6a-027d-11e7-848f-991b20545aa8.png)

**Comment by idleberg** [comment]
Before I release a new version, could you test the latest master?

**Comment by fake-name** [comment]
Sure, give me a bit to remember how to do so.

**Comment by fake-name** [comment]
I am a little curious why the `package.json` in the repo seems to refer to the project as `https://github.com/idleberg/sublimetext-gulpfile.js`, though.

**Comment by idleberg** [comment]
> I am a little curious why the package.json in the repo seems to refer to the project as https://github.com/idleberg/sublimetext-gulpfile.js, though.

Both, `package.json` and `gulpfile.js` are generic files I use to lint my packages on Travis CI. Since Sublime Text does not use `package.json` anywhere, I didn't bother to change that. Pure laziness!

**Comment by fake-name** [comment]
I kind of guessed. I didn't think there was much that travis could do with this package in general.
